poll/urls.py
from django.conf.urls import url



from . import views

urlpatterns = [
	# /poll/
    url(r'^$', views.index, name= 'index'),
    url(r'^help_me/$', views.help_me, name= 'help_me'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail_question, name='detail_question'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^vote/$', views.vote, name= 'vote'),
    
]

sipython/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^poll/', include('poll.urls', namespace='poll')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/models.py
from django.db import models



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__ (self):
    	return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    image = models.ImageField(null=True, blank=True)


    def __str__ (self):
    	return self.choice_text

poll/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render

from .models import Question, Choice

# Create your views here.
def index(request):
	context = {}
	questions_query = Question.objects.all()
	context ['questions'] = questions_query
	return render(request, 'poll/index.html', context)

def help_me(request):
	context = {}
	return render(request, 'poll/help_me.html', context)

def detail_question(request, question_id):
	context ={}
	question = Question.objects.get(id=question_id)
	context ['question'] = question
	return render (request, 'poll/detail_question.html', context)

def vote(request):
	context = {}
	choice_id = request.POST['choice']
	selected_choice = Choice.objects.get(id=int(choice_id))
	selected_choice.votes += 1
	selected_choice.save()
	return HttpResponseRedirect(reverse('poll:results', args=(selected_choice.question.id,)))

def results(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'poll/results.html', {'question': question})

templates/poll/detail_question.html
{% load staticfiles %}

<html>
	<head>
		<title>This is Poll</title>
		<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="row">
			<h1>{{question.question_text}}</h1><br />

			<form action="{% url 'poll:vote'  %}" method="post">

			{% csrf_token %}
			
			<ul style="list-style-type: none">
			{%  for choice in question.choice_set.all %}
				<li>
				<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
				{{choice.choice_text}}
				{% if choice.image %}
				<br /><img class ="img-circle" src = "{{choice.image.url|default_if_none:'#' }}" height=150 width= 150>
				{% endif %}
				</li>
				
			{% endfor %}
			</ul>
			<br><input type="submit" value="Vote" /></br>
			</form>
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="{% static 'js/bootstrap.js' %}"></script>
	</body>
</html>

templates/poll/help_me.html
{<html>
<h1>Tolooooongg</h1>
</html>}

templates/poll/index.html
{% load staticfiles %}

<html>
	<head>
		<title>This is Poll</title>
		<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="row">
			<h1>Heihooo, welcome to poll!</h1>
			<p class="lead">This is an app which can poll something.</p>
			<ol>
			{% for quest in questions %}
				<li>
					<a href="{% url 'poll:detail_question' quest.id %}">{{quest.question_text}}</a>
				</li>
			{% endfor %}
			</ol>

			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="{% static 'js/bootstrap.js' %}"></script>
	</body>
</html>

templates/poll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail_question' question.id %}">Vote again?</a>